const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Platform,
		C3.Behaviors.jumpthru,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Teclado: 0},
	{Áudio: 0},
	{fundoFase1: 0},
	{moeda: 0},
	{derrota: 0},
	{textoDerrota: 0},
	{botaovoltar: 0},
	{telamenu: 0},
	{fundomenu: 0},
	{botaoplay: 0},
	{telavitoria: 0},
	{botaovitoria: 0},
	{fase2fundo: 0},
	{plataforma: 0},
	{plataforma2: 0},
	{plataforma3: 0},
	{plataforma4: 0},
	{coletavel: 0},
	{Plataforma: 0},
	{personagem1: 0},
	{PularAtravés: 0},
	{chao: 0},
	{lixo: 0},
	{Sólido: 0},
	{parede: 0},
	{Morte: 0},
	{VoceCaiuNoBuraco: 0},
	{aNaturezaPrecisaDeVoce: 0},
	{imagemderrotafloresta: 0},
	{titulojogo: 0},
	{cadaaçãopode: 0},
	{paredefase1parafase2: 0},
	{tronco: 0},
	{buraco: 0},
	{paredefase2para3: 0},
	{colisaoplataforma: 0},
	{textomoeda: 0},
	{caminholiberado: 0},
	{espinhos: 0},
	{lixopegos: 0},
	{fundofase3: 0},
	{Senóide: 0},
	{"1plataformafase": 0},
	{Fixar: 0},
	{barriltoxico: 0},
	{barrispegos: 0},
	{barrislimpos: 0},
	{muda: 0},
	{mudaspegas: 0},
	{mudasColetadas: 0},
	{paredefase3para4: 0},
	{fundofinal: 0},
	{arvoresplantadas: 0},
	{jogadorarvore: 0},
	{NATUREZARESTAURADA: 0},
	{aperteE: 0},
	{lixopegar: 0},
	{moedaspegas: 0},
	{qtdarvores: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	fundoFase1: class extends self.ISpriteInstance {},
	moeda: class extends self.ISpriteInstance {},
	derrota: class extends self.ISpriteInstance {},
	textoDerrota: class extends self.ITextInstance {},
	botaovoltar: class extends self.ISpriteInstance {},
	telamenu: class extends self.ISpriteInstance {},
	fundomenu: class extends self.ISpriteInstance {},
	botaoplay: class extends self.ISpriteInstance {},
	telavitoria: class extends self.ISpriteInstance {},
	botaovitoria: class extends self.ISpriteInstance {},
	fase2fundo: class extends self.ISpriteInstance {},
	plataforma: class extends self.ISpriteInstance {},
	plataforma2: class extends self.ISpriteInstance {},
	plataforma3: class extends self.ISpriteInstance {},
	plataforma4: class extends self.ISpriteInstance {},
	coletavel: class extends self.ISpriteInstance {},
	personagem1: class extends self.ISpriteInstance {},
	chao: class extends self.ISpriteInstance {},
	lixo: class extends self.ISpriteInstance {},
	parede: class extends self.ISpriteInstance {},
	Morte: class extends self.ISpriteInstance {},
	VoceCaiuNoBuraco: class extends self.ISpriteInstance {},
	aNaturezaPrecisaDeVoce: class extends self.ISpriteInstance {},
	imagemderrotafloresta: class extends self.ISpriteInstance {},
	titulojogo: class extends self.ISpriteInstance {},
	cadaaçãopode: class extends self.ISpriteInstance {},
	paredefase1parafase2: class extends self.ISpriteInstance {},
	tronco: class extends self.ISpriteInstance {},
	buraco: class extends self.ISpriteInstance {},
	paredefase2para3: class extends self.ISpriteInstance {},
	colisaoplataforma: class extends self.ISpriteInstance {},
	textomoeda: class extends self.ITextInstance {},
	caminholiberado: class extends self.ITextInstance {},
	espinhos: class extends self.ISpriteInstance {},
	lixopegos: class extends self.ITextInstance {},
	fundofase3: class extends self.ISpriteInstance {},
	_1plataformafase: class extends self.ISpriteInstance {},
	barriltoxico: class extends self.ISpriteInstance {},
	barrispegos: class extends self.ITextInstance {},
	barrislimpos: class extends self.ITextInstance {},
	muda: class extends self.ISpriteInstance {},
	mudaspegas: class extends self.ITextInstance {},
	mudasColetadas: class extends self.ITextInstance {},
	paredefase3para4: class extends self.ISpriteInstance {},
	fundofinal: class extends self.ISpriteInstance {},
	arvoresplantadas: class extends self.ITextInstance {},
	jogadorarvore: class extends self.ISpriteInstance {},
	NATUREZARESTAURADA: class extends self.ITextInstance {},
	aperteE: class extends self.ITextInstance {}
}